### ISSUE TITLE
(UICollectionView) numberOfSectionsInCollectionView is never called

### ISSUE THREAD

**Issue by cs-edouard** [garrefa/AXMagicIdentifiers#1]
When I setup the lib, the collectionView never call the UICollectionViewDataSource '- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView *)collectionView'!!!
I know it's weird, but we try couple of time to add and removed the lib, and each time the lib make buggy the UICollectionViewDataSource.

**Comment by garrefa** [comment]
Hey Edouard, thank you.

I just released version 1.0.6 with the bug fix, please check that.

**Comment by cs-edouard** [comment]
Great it's working perfectly, thanks
